### ISSUE TITLE
Lectures Outline (1st part of the fullday Workshop)

### ISSUE THREAD

**Issue by yguenduez** [rust-basel/htmx-workshop-meetup-10#3]
A proposal of a list of things we want to teach in the lecture part - and can be used in the project part. By far not complete. If you have ideas, please add them as well.

- **Introducing axum**: for people that do not know it - maybe showing how to return something from a handler (get) - and post something - could already be enough).
- **How to render html with axum and askama**: Explaining how it works - example could be: Creating a struct, #[derive(Template)] with the corresponding .html template. Change members in the struct - and see how those are replaced in the {{}} (handlebars?/placeholders) of the template.
- **How to add htmx to our html**: Adding the htmx cdn to the base.html template?
- **Small examples on htmx**: That is prob the biggest part of the lectures - : Can be arbitrary examples: like: click button -> exchange with fetched content - I myself only did the super basic stuff with htmx so far - so you might have more ideas here

**Comment by yguenduez** [comment]
Do we want to do a mdbook for the lectures (like e.g. this: https://rust-basel.ch/fullstack-rust-workshop/ - but much smaller though) - or plain old slides?

**Comment by SilenLoc** [comment]
I like a md book :)

**Comment by SilenLoc** [comment]
How to add htmx:

I like the vendor approach and then hosting it under "_assets" then refrencing it in the doc with that.

Like this we will never have a version problem.

**Comment by SilenLoc** [comment]
Small examples on htmx:

A form with a target / swap

Is the best I think.

Very important to show here is that locality of behaviour is something you get for free and that the storage is the backend this also means: it is almost impssible to have data drift between client and server.

"HTML with interactivity"
