### ISSUE TITLE
Project Outline (2nd part of the fullday Workshop)

### ISSUE THREAD

**Issue by yguenduez** [rust-basel/htmx-workshop-meetup-10#4]
Just a proposal for the project (taken from [this discussion](https://github.com/rust-basel/organization/issues/4)). If you have other/more ideas, please add them here.

Given input, a QR code is generated that is displayed next to the inputs. As an inspiration see the below image:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/3e409b8e-b55f-4f74-ac2d-7262f3de7b1d">

As this already quite big I would propose that inputs, like an IBAN and a name is already enough.
We then would have to define, what kind of QR code that is. For the QR code generation, we could just provide code, that generates the QR given certain input.

The main task of the attendes would be to build

- input fields
- kind of a "submit button"
- A placeholder for the qr code, that will swapped for the generated QR code form the server.

Of course this could be done in the browser alone, but we want to show some htmx + rust server interaction.

**Comment by yguenduez** [comment]
Just an Idea for the state: We could also introduce some state (fake login? - where we only store the name of the person). That name then could be used as "issuer" if the qr code payment.

**Comment by SilenLoc** [comment]
> Just an Idea for the state: We could also introduce some state (fake login? - where we only store the name of the person). That name then could be used as "issuer" if the qr code payment.

Yes something like that, just that it is clear that you can not really do it without server state.

I do not want to explode the scope so one feature which needs to be backend handled is great to show how great htmx is.

**Comment by yguenduez** [comment]
As the showcase stands, I can close this one :)
