### ISSUE TITLE
Create a way to create a QR code

### ISSUE THREAD

**Issue by SilenLoc** [rust-basel/htmx-workshop-meetup-10#5]
One cool thing of htmx is that we can create the whole vertical slice in one go if we want.

But I would start with a pure function to create the qr code so we have a clear input and output.

**Comment by yguenduez** [comment]
Agree. Researched a bit on how to create a swiss QR-IBAN. But this seems a little bit out of scope (There is a [standard](https://www.six-group.com/dam/download/banking-services/standardization/qr-bill/ig-qr-bill-v2.2-en.pdf) for it). But there are some repos, which already create this one (e.g. [this one](https://github.com/schoero/SwissQRBill)).

We could also just encode something into json (+base64) - (if you then scan it this with e.g. google lens, you just see the json). For this one could just use the qrcode crate (like [here](https://github.com/yguenduez/qr-for-free-webonly/blob/main/frontend/src/main.rs#L70)).
So then we would have input fields -> json -> qr_data_url, that you can render as image for example.

**Comment by SilenLoc** [comment]
For now I created this: 
![image](https://github.com/user-attachments/assets/10585d7d-05b9-4919-b76b-94b67f955428)

We need to iterate over it of course

**Comment by SilenLoc** [comment]
I consider this done and create a next ticket :)
